AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index2.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTimeApi2:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
